ALTER TABLE products ADD COLUMN rating DECIMAL(3, 2) DEFAULT 0;
ALTER TABLE products ADD COLUMN reviews_count INT DEFAULT 0;
ALTER TABLE products ADD COLUMN is_new BOOLEAN DEFAULT FALSE;
ALTER TABLE products ADD COLUMN is_sale BOOLEAN DEFAULT FALSE;
